# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3f01d05b99c4cb24a73533ff2aa693669eb46c6cf7b7d53dfc6343adc85b496104ff1593d029b81956f175b2e2834050d8eead89995c304d2333ab41843e952

test:
  secret_key_base: c343501d9b4027e5eff3e4b8adfeb45ff454bffe7c459d6c35ab2038eea074d8df6fafe7d7051bd6c13e7ad6cb5fbac0a86a3928c3d4d388035e0cf18b2d685a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
